openapi: 3.0.0
info:
  title: Image Management API
  version: 1.0.0
  description: API to manage images
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Images
    description: API to manage images
paths:
  /images/list-images:
    get:
      summary: Lists all images
      tags: [Images]
      responses:
        '200':
          description: A list of images
          content:
            text/html:
              schema:
                type: string
                example: "<html>...</html>"
  /images/{imageName}:
    get:
      summary: Retrieve a single image by name
      tags: [Images]
      parameters:
        - in: path
          name: imageName
          required: true
          schema:
            type: string
          description: The name of the image
          examples:
            example1:
              summary: Elephant
              value: "elefant.jpg"
            example2:
              summary: Gorilla
              value: "gorilla.jpg"
            example3:
              summary: Crocodile
              value: "crocodile.jpg"
      responses:
        '200':
          description: An image file
          content:
            image/jpeg:
              schema:
                type: string
                format: binary

